services:
  HackatonFiap.Users:
    build:
      context: .
      dockerfile: src/HackatonFiap.Users.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Default=Server=localhost,1433;Database=HackatonFiapUsersDb;User Id=sa;Password=Your_password123;TrustServerCertificate=true;
      - Jwt__Issuer=conexaosolidaria.local
      - Jwt__Audience=conexaosolidaria.clients
      - Jwt__Key=
      - Owner__Password=
      - ASPNETCORE_ENVIRONMENT=Development
