apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackatonfiap-users
  namespace: hackatonfiap
  labels:
    app: hackatonfiap-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackatonfiap-users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hackatonfiap-users
        azure.workload.identity/use: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: sa-hackatonfiap-users
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "hackatonfiap-users-secrets"
      containers:
        - name: hackatonfiap-users
          image: fcgregistry.azurecr.io/hackatonfiap-users:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8080
              name: metrics
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: hackatonfiap-users-secret
          env:
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: hackatonfiap-users-secret
                  key: ConnectionStrings__Default
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: hackatonfiap-users-secret
                  key: Jwt__Key
            - name: Owner__Password
              valueFrom:
                secretKeyRef:
                  name: hackatonfiap-users-secret
                  key: Owner__Password
            - name: Jwt__Issuer
              value: "conexaosolidaria.local"
            - name: Jwt__Audience
              value: "conexaosolidaria.clients"
            - name: Owner__Email
              value: "owner@conexaosolidaria.org"
            - name: Owner__Document
              value: "52998224725"
            - name: Owner__Name
              value: "Owner"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
